# This is a basic workflow to help you get started with Actions

name: check-in

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 18 * * *"  # scheduled at 06:00 (UTC+8) everyday

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: python index.py "_MHYUUID=0f1ce386-b144-49fc-8b7c-9ea6be90d9e9; UM_distinctid=183487389b34f2-00a1ecac616f59-26021d51-1fa400-183487389b413c3; _ga=GA1.2.1029194557.1663367876; smidV2=202209170637555f20f606c125b900d50eee7395b84e3200d8e1397c277e710; _gid=GA1.2.2072382649.1664044636; DEVICEFP_SEED_ID=b0ca6982bce39f1a; DEVICEFP_SEED_TIME=1664056090152; DEVICEFP=38d7eb371e30e; CNZZDATA1275023096=766666546-1663364636-%7C1664055889; ltoken=IP0aCjdChm1PHjqcGLPtE2DMz9dlZYIapMw5wNHJ; ltuid=185342214; cookie_token=WkFS38J2lpTcvhuSVQJ6Ll9LvxUbqWabdngyMD9F; account_id=185342214; _gat=1; .thumbcache_a5f2da7236017eb7e922ea0d742741d5=pTsv/un+ofHjGCxwdp1BC6w6nQaL5zlecjHD9CAuqLR3R9gEpk39z5mFkuR7O8S6IuKk3niLiC01x6drT/pquw%3D%3D"

