# This is a basic workflow to help you get started with Actions

name: check-in

# Controls when the workflow will run
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 18 * * *"  # scheduled at 06:00 (UTC+8) everyday

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  checkin:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install requests
          
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: python3 ./index.py
    env:
      #设置secrets的环境变量
      GENSHIN_COOKIE: ${{ secrets.GENSHIN_COOKIE }}

